<?php

/**
 * @file
 * Module file for conjoc.
 */

/**
 * @defgroup conjoc Example: Menu
 * @ingroup examples
 * @{
 * Demonstrates uses of the Menu APIs in Drupal.
 *
 * The Page Example module also talks about the menu system, as well
 * as how to use menu arguments to generate pages.
 *
 * @see hook_menu()
 * @see hook_menu_alter()
 * @see hook_menu_link_alter()
 * @see conjoc
 * @see page_conjoc()
 */

/**
 * Implements hook_menu().
 *
 * A simple example which defines a page callback and a menu entry.
 */
//require_once('conjoc_webForm.inc');

function conjoc_menu() {
  // Menu items are defined by placing them in an $items array. The array key
  // (in this case 'conjoc') is the path that defines the menu router
  // entry, so the page will be accessible from the URL
  // example.com/examples/conjoc.

  /*
    LENGADOCIAN OLD WAY
  */

  // Search page w/ajax autocomplete
/*
  $items['conjoc/verb_autocomplete'] = array(
    'title' => t("Old Conjugador occitan dialecte Lengadocian"),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ajax_conjoc_verb_autocomplete'),
    //    'page callback' => '_conjoc_menu_page',
    'access arguments' => array('access conjoc'),
    'file' => 'conjoc_webForm.inc',
    'weight' => 10,
  );

  $items['conjoc/verb_autocomplete_callback'] = array(
    'page callback' => 'ajax_conjoc_verb_autocomplete_callback',
    'file' => 'conjoc_webForm.inc',
    'type' => MENU_CALLBACK,
    'access arguments' => array('access conjoc'),
  );

  $items['conjoc/verb_autocomplete/usuals'] = array(
    'title' => t("Conjugador occitan"),
    'page callback' => '_conjoc_menu_page',
    'access arguments' => array('access conjoc'),
    'file' => 'conjoc_webForm.inc',
    'type' => MENU_CALLBACK,
  );
*/
  $items['conjoc/verb_autocomplete/better_see'] = array(
    'title' => t("Conjugador occitan"),
    'page callback' => '_conjoc_menu_page',
    'access arguments' => array('access conjoc'),
    'file' => 'conjoc_webForm.inc',
    'type' => MENU_CALLBACK,
  );

  $items['conjoc/verb_autocomplete/singles'] = array(
    'title' => t("Conjugador occitan"),
    'page callback' => '_conjoc_menu_page',
    'access arguments' => array('access conjoc'),
    'file' => 'conjoc_webForm.inc',
    'type' => MENU_CALLBACK,
  );

  $items['conjoc/verb_autocomplete/top20'] = array(
    'title' => t("Conjugador occitan"),
    'page callback' => '_conjoc_menu_page',
    'access arguments' => array('access conjoc'),
    'file' => 'conjoc_webForm.inc',
    'type' => MENU_CALLBACK,
  );

/*
  $items['conjoc/TEI/exportLengadocian'] = array(
    'title' => t("Export TEI Lengadocian"),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('tei_export_lengadocian_all'),
    'access arguments' => array('access conjoc'),
    'file' => 'conjoc_webForm.inc',
    'weight' => 10,
  );


  $items['conjoc/Indexation/allLengadocian'] = array(
    'title' => t("Indexation Lengadocian"),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('indexation_lengadocian_all'),
//    'access arguments' => array('administer conjoc'),
    'access arguments' => array('no access'),
    'file' => 'conjoc_webForm.inc',
    'weight' => 10,
  );
*/
  /*
    LENGADOCIAN
  */

  $items['conjoc/lengadocian'] = array(
    'title' => t("Conjugador occitan dialecte lengadocian"),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ajax_lengadocian_verb_autocomplete'),
    'access arguments' => array('access conjoc'),
    'file' => 'conjoc_lengadocian_webForm.inc',
    'weight' => 10,
  );

  $items['conjoc/verb_autocomplete_lengadocian_callback'] = array(
    'page callback' => 'ajax_lengadocian_verb_autocomplete_callback',
    'file' => 'conjoc_lengadocian_webForm.inc',
    'type' => MENU_CALLBACK,
    'access arguments' => array('access conjoc'),
  );

/*  
  $items['conjoc/verb_autocomplete_gasc_validate'] = array(
    'page callback' => 'ajax_conjoc_verb_autocomplete_validate',
    'file' => 'conjoc_lengadocian_webForm.inc',
    'type' => MENU_CALLBACK,
    'access arguments' => array('access conjoc'),
  );
*/  
  
  $items['lengadocian/verb_autocomplete_leng_submit'] = array(
    'page callback' => 'ajax_lengadocian_verb_autocomplete_submit',
    'file' => 'conjoc_lengadocian_webForm.inc',
    'type' => MENU_CALLBACK,
    'access arguments' => array('access conjoc'),
  );
  
  $items['lengadocian/verb_autocomplete_callback'] = array(
    'page callback' => 'ajax_lengadocian_verb_autocomplete_callback',
    'file' => 'conjoc_lengadocian_webForm.inc',
    'type' => MENU_CALLBACK,
    'access arguments' => array('access conjoc'),
  );

  $items['lengadocian/verb_autocomplete/usuals'] = array(
    'title' => t("Conjugador occitan"),
    'page callback' => '_lengadocian_menu_page',
    'access arguments' => array('access conjoc'),
    'file' => 'conjoc_lengadocian_webForm.inc',
    'type' => MENU_CALLBACK,
  );

  $items['lengadocian/verb_autocomplete/better_see'] = array(
    'title' => t("Conjugador occitan"),
    'page callback' => '_lengadocian_menu_page',
    'access arguments' => array('access conjoc'),
    'file' => 'conjoc_lengadocian_webForm.inc',
    'type' => MENU_CALLBACK,
  );

  $items['lengadocian/verb_autocomplete/singles'] = array(
    'title' => t("Conjugador occitan"),
    'page callback' => '_lengadocian_menu_page',
    'access arguments' => array('access conjoc'),
    'file' => 'conjoc_lengadocian_webForm.inc',
    'type' => MENU_CALLBACK,
  );

  $items['lengadocian/verb_autocomplete/top20'] = array(
    'title' => t("Conjugador occitan"),
    'page callback' => '_conjoc_menu_page',
    'access arguments' => array('access conjoc'),
    'file' => 'conjoc_lengadocian_webForm.inc',
    'type' => MENU_CALLBACK,
  );

  $items['lengadocian/TEI/exportLengadocian'] = array(
    'title' => t("Export TEI Lengadocian"),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('tei_export_lengadocian_all'),
    'access arguments' => array('administer conjoc'),
    'file' => 'conjoc_lengadocian_webForm.inc',
    'weight' => 10,
  );

/*
  $items['lengadocian/Indexation/allLengadocian'] = array(
    'title' => t("Indexation Lengadocian"),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('indexation_lengadocian_all'),
    'access arguments' => array('administer conjoc'),
    'file' => 'conjoc_lengadocian_webForm.inc',
    'weight' => 10,
  );

  $items['lengadocian/Indexation/byIncrement'] = array(
    'title' => t("Indexation lengadocian by increment"),
    'page callback' => 'conjoc_cron',
    'access arguments' => array('administer conjoc'),
    'weight' => 10,
  );
*/

  $items['lengadocian/Indexation/searchform'] = array(
    'title' => t("Indexation search form"),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('indexation_searchform'),
    'access arguments' => array('access conjoc'),
    'file' => 'conjoc_lengadocian_webForm.inc',
    'weight' => 10,
  );

  $items['conjoc/indexation_search/%/%'] = array(
    'title' => 'Indexation search',
    'page callback' => 'process_URL_arguments',
    'file' => 'conjoc_lengadocian_webForm.inc',
    'page arguments' => array(2,3),
    'access callback' => TRUE,
  );

  $items['conjoc/verb_autocomplete_indexation_callback'] = array(
    'page callback' => 'verb_autocomplete_indexation_callback',
    'file' => 'conjoc_lengadocian_webForm.inc',
    'type' => MENU_CALLBACK,
    'access arguments' => array('access conjoc'),
  );

  $items['conjoc/verb_autocomplete_indexation_submit'] = array(
    'page callback' => 'verb_autocomplete_indexation_submit',
    'file' => 'conjoc_lengadocian_webForm.inc',
    'type' => MENU_CALLBACK,
    'access arguments' => array('access conjoc'),
  );

  /*
    PROVENCAL
 

  $items['conjoc/provencal'] = array(
    'title' => t("Conjugador occitan dialecte provencal"),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ajax_provencal_verb_autocomplete'),
    'access arguments' => array('access conjoc'),
    'file' => 'conjoc_provencal_webForm.inc',
    'weight' => 10,
  );

  $items['conjoc/verb_autocomplete_prov_callback'] = array(
    'page callback' => 'ajax_provencal_verb_autocomplete_callback',
    'file' => 'conjoc_provencal_webForm.inc',
    'type' => MENU_CALLBACK,
    'access arguments' => array('access conjoc'),
  );
  */
  
  /*
    GASCON
  */

  $items['conjoc/gascon'] = array(
    'title' => t("Conjugador occitan dialecte gascon"),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ajax_gascon_verb_autocomplete'),
    'access arguments' => array('access conjoc'),
    'file' => 'conjoc_gascon_webForm.inc',
    'weight' => 10,
  );

  $items['conjoc/verb_autocomplete_gasc_callback'] = array(
    'page callback' => 'ajax_gascon_verb_autocomplete_callback',
    'file' => 'conjoc_gascon_webForm.inc',
    'type' => MENU_CALLBACK,
    'access arguments' => array('access conjoc'),
  );

/*  
  $items['conjoc/verb_autocomplete_gasc_validate'] = array(
    'page callback' => 'ajax_conjoc_verb_autocomplete_validate',
    'file' => 'conjoc_gascon_webForm.inc',
    'type' => MENU_CALLBACK,
    'access arguments' => array('access conjoc'),
  );
*/  

  
  $items['conjoc/verb_autocomplete_gasc_submit'] = array(
    'page callback' => 'ajax_conjoc_verb_autocomplete_submit',
    'file' => 'conjoc_gascon_webForm.inc',
    'type' => MENU_CALLBACK,
    'access arguments' => array('access conjoc'),
  );

  /*
    D E B U G
  */
/*$
  $items['conjoc/debug'] = array(
    'title' => t("Conjugador occitan dialecte debug"),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ajax_debug_verb_autocomplete'),
//    'access arguments' => array('access conjoc'),
    'access arguments' => array('no access'),
    'file' => 'conjoc_debug_webForm.inc',
    'weight' => 10,
  );

  $items['conjoc/verb_autocomplete_debug_callback'] = array(
    'page callback' => 'ajax_debug_verb_autocomplete_callback',
    'file' => 'conjoc_debug_webForm.inc',
    'type' => MENU_CALLBACK,
//    'access arguments' => array('access conjoc'),
    'access arguments' => array('no access'),

  );

  $items['conjoc/verb_autocomplete_debug_submit'] = array(
    'page callback' => 'ajax_debug_verb_autocomplete_submit',
    'file' => 'conjoc_debug_webForm.inc',
    'type' => MENU_CALLBACK,
//    'access arguments' => array('access conjoc'),
    'access arguments' => array('no access'),
  );

  $items['conjoc/debug_submit'] = array(
    'page callback' => 'ajax_debug_verb_autocomplete_submit',
    'file' => 'conjoc_debug_webForm.inc',
    'type' => MENU_CALLBACK,
  );

  $items['conjoc/debug_TEI_submit'] = array(
    'page callback' => 'ajax_debug_verb_autocomplete_submit',
    'file' => 'conjoc_debug_webForm.inc',
    'type' => MENU_CALLBACK,
    'access arguments' => array('access conjoc'),
  );
*/
  /*
    F I N  D E B U G
  */

  $items['admin/settings/conjoc'] = array(
    'title' => t('Conjoc module settings'),
    'description' => 'Conjoc settings page',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('conjoc_admin'),
    'access arguments' => array('administer conjoc settings'),
    'type' => MENU_NORMAL_ITEM,
   );

  return $items;
} // conjoc_menu

function conjoc_cron() {
  if (variable_get('conjoc_indexation_enabled', false)){
     $manager = new ConjugationLengadocianManager();
     $manager->processIndexation();
     $manager = new ConjugationGasconManager();
     $manager->processIndexation();
  }
}

function conjoc_admin() {
  $form = array();

  $form['conjoc_indexation_Lengadocian_enabled'] = array(
    				     '#type' => 'checkbox',
    				     '#title' => t('Enable indexation Lengadocian'),
    				     '#default_value' => variable_get('conjoc_indexation_Lengadocian_enabled', false),
    				     '#description' => t("Enable the indexation sequence for lengadocian dialect. When completed it is set to false"),
  );

  $form['conjoc_indexation_Lengadocian_reset'] = array(
    				     '#type' => 'checkbox',
    				     '#title' => t('reset increment for Lengadocian indexation'),
    				     '#default_value' => variable_get('conjoc_indexation_Lengadocian_reset', false),
    				     '#description' => t("Reset the lengadocian indexation increment to 0"),
  );

  $form['conjoc_indexation_Lengadocian_increment'] = array(
  				       '#type' => 'textfield', 
  				       '#title' => t('Lengadocian Increment'), 
  				       '#default_value' => variable_get('conjoc_indexation_Lengadocian', 0), 
  				       '#size' => 2, 
  				       '#required' => FALSE,
  				       '#disabled' => FALSE,
  );

  $form['conjoc_indexation_Lengadocian_totalIncrements'] = array(
  				       '#type' => 'textfield', 
  				       '#title' => t('Lengadocian total increments'), 
  				       '#default_value' => variable_get('conjoc_indexation_Lengadocian_totalIncrements', 0), 
  				       '#size' => 2, 
  				       '#required' => FALSE,
  				       '#disabled' => TRUE,
  );

  $form['conjoc_indexation_Lengadocian_verbsindexed'] = array(
  				       '#type' => 'textfield', 
  				       '#title' => t('# Lengadocian verbs indexed'), 
  				       '#default_value' => variable_get('conjoc_indexation_Lengadocian_verbsindexed', 0), 
  				       '#size' => 10, 
  				       '#required' => FALSE,
  				       '#disabled' => TRUE,
  );

  $form['conjoc_indexation_Lengadocian_verbstoindex'] = array(
  				       '#type' => 'textfield', 
  				       '#title' => t('# Lengadocian verbs left to index'), 
  				       '#default_value' => variable_get('conjoc_indexation_Lengadocian_verbstoindex', 0), 
  				       '#size' => 10, 
  				       '#required' => FALSE,
  				       '#disabled' => TRUE,
  );


/*G A S C O N*/

  $form['conjoc_indexation_Gascon_enabled'] = array(
    				     '#type' => 'checkbox',
    				     '#title' => t('Enable indexation Gascon'),
    				     '#default_value' => variable_get('conjoc_indexation_Gascon_enabled', false),
    				     '#description' => t("Enable the indexation sequence for gascon dialect. When completed it is set to false"),
  );

  $form['conjoc_indexation_Gascon_reset'] = array(
    				     '#type' => 'checkbox',
    				     '#title' => t('reset increment for Gascon indexation'),
    				     '#default_value' => variable_get('conjoc_indexation_Gascon_reset', false),
    				     '#description' => t("Reset the gascon indexation increment to 0"),
  );

  $form['conjoc_indexation_Gascon_increment'] = array(
  				       '#type' => 'textfield', 
  				       '#title' => t('Gascon Increment'), 
  				       '#default_value' => variable_get('conjoc_indexation_Gascon', 0), 
  				       '#size' => 2, 
  				       '#required' => FALSE,
  				       '#disabled' => FALSE,
  );

  $form['conjoc_indexation_Gascon_totalIncrements'] = array(
  				       '#type' => 'textfield', 
  				       '#title' => t('Gascon total increments'), 
  				       '#default_value' => variable_get('conjoc_indexation_Gascon_totalIncrements', 0), 
  				       '#size' => 2, 
  				       '#required' => FALSE,
  				       '#disabled' => TRUE,
  );

  $form['conjoc_indexation_Gascon_verbsindexed'] = array(
  				       '#type' => 'textfield', 
  				       '#title' => t('# Gascon verbs indexed'), 
  				       '#default_value' => variable_get('conjoc_indexation_Gascon_verbsindexed', 0), 
  				       '#size' => 10, 
  				       '#required' => FALSE,
  				       '#disabled' => TRUE,
  );

  $form['conjoc_indexation_Gascon_verbstoindex'] = array(
  				       '#type' => 'textfield', 
  				       '#title' => t('# Gascon verbs left to index'), 
  				       '#default_value' => variable_get('conjoc_indexation_Gascon_verbstoindex', 0), 
  				       '#size' => 10, 
  				       '#required' => FALSE,
  				       '#disabled' => TRUE,
  );

  return system_settings_form($form);
}

function conjoc_admin_validate($form, &$form_state) {
  $newValue     = $form_state['values']['conjoc_indexation_enabled'];
  $currentValue = variable_get('conjoc_indexation_enabled', false);
  $increment    = $form_state['values']['conjoc_indexation_increment'];

  if ( $newValue && ($newValue != $currentValue) ){
     variable_set('conjoc_indexation_increment', '0');
     drupal_set_message(t("Indexation increment reset $currentValue $newValue"));
  } // if 

  if (!is_numeric($increment)) {
    form_set_error('conjoc_indexation_increment', t('You must enter an integer.'));
  }
  elseif ($increment < 0) {
    form_set_error('conjoc_indexation_increment', t('increment must be positive.'));
  }
// TO DO validate maximum value
}

/**
 * Implements hook_permission().
 *
 * Provides a demonstration access string.
 */
function conjoc_permission() {
  return array(
    'access conjoc' => array(
      'title' => t('Access the protected conjoc menu'),
    ),
    'administer conjoc' => array(
      'title' => t('Administer conjoc content'),
    ),
  );

}

