<?php

/**
 * @file
 * Module file for conjoc.
 */

/**
 * @defgroup conjoc Example: Menu
 * @ingroup examples
 * @{
 * Demonstrates uses of the Menu APIs in Drupal.
 *
 * The Page Example module also talks about the menu system, as well
 * as how to use menu arguments to generate pages.
 *
 * @see hook_menu()
 * @see hook_menu_alter()
 * @see hook_menu_link_alter()
 * @see conjoc
 * @see page_conjoc()
 */

/**
 * Implements hook_menu().
 *
 * A simple example which defines a page callback and a menu entry.
 */
//require_once('conjoc_webForm.inc');

function conjoc_menu() {
  // Menu items are defined by placing them in an $items array. The array key
  // (in this case 'conjoc') is the path that defines the menu router
  // entry, so the page will be accessible from the URL
  // example.com/examples/conjoc.

  /*
    LENGADOCIAN OLD WAY
  */

  // Search page w/ajax autocomplete
  $items['conjoc/verb_autocomplete'] = array(
    'title' => t("Old Conjugador occitan dialecte Lengadocian"),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ajax_conjoc_verb_autocomplete'),
    //    'page callback' => '_conjoc_menu_page',
    'access arguments' => array('access conjoc'),
    'file' => 'conjoc_webForm.inc',
    'weight' => 10,
  );

  $items['conjoc/verb_autocomplete_callback'] = array(
    'page callback' => 'ajax_conjoc_verb_autocomplete_callback',
    'file' => 'conjoc_webForm.inc',
    'type' => MENU_CALLBACK,
    'access arguments' => array('access conjoc'),
  );

  $items['conjoc/verb_autocomplete/usuals'] = array(
    'title' => t("Conjugador occitan"),
    'page callback' => '_conjoc_menu_page',
    'access arguments' => array('access conjoc'),
    'file' => 'conjoc_webForm.inc',
    'type' => MENU_CALLBACK,
  );

  $items['conjoc/verb_autocomplete/better_see'] = array(
    'title' => t("Conjugador occitan"),
    'page callback' => '_conjoc_menu_page',
    'access arguments' => array('access conjoc'),
    'file' => 'conjoc_webForm.inc',
    'type' => MENU_CALLBACK,
  );

  $items['conjoc/verb_autocomplete/singles'] = array(
    'title' => t("Conjugador occitan"),
    'page callback' => '_conjoc_menu_page',
    'access arguments' => array('access conjoc'),
    'file' => 'conjoc_webForm.inc',
    'type' => MENU_CALLBACK,
  );

  $items['conjoc/verb_autocomplete/top20'] = array(
    'title' => t("Conjugador occitan"),
    'page callback' => '_conjoc_menu_page',
    'access arguments' => array('access conjoc'),
    'file' => 'conjoc_webForm.inc',
    'type' => MENU_CALLBACK,
  );
/*
  $items['conjoc/TEI/exportLengadocian'] = array(
    'title' => t("Export TEI Lengadocian"),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('tei_export_lengadocian_all'),
    'access arguments' => array('access conjoc'),
    'file' => 'conjoc_webForm.inc',
    'weight' => 10,
  );
*/

  $items['conjoc/Indexation/allLengadocian'] = array(
    'title' => t("Indexation Lengadocian"),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('indexation_lengadocian_all'),
    'access arguments' => array('access conjoc'),
    'file' => 'conjoc_webForm.inc',
    'weight' => 10,
  );

  /*
    LENGADOCIAN
  */

  $items['conjoc/lengadocian'] = array(
    'title' => t("Conjugador occitan dialecte lengadocian"),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ajax_lengadocian_verb_autocomplete'),
    'access arguments' => array('access conjoc'),
    'file' => 'conjoc_lengadocian_webForm.inc',
    'weight' => 10,
  );

  $items['conjoc/verb_autocomplete_lengadocian_callback'] = array(
    'page callback' => 'ajax_lengadocian_verb_autocomplete_callback',
    'file' => 'conjoc_lengadocian_webForm.inc',
    'type' => MENU_CALLBACK,
    'access arguments' => array('access conjoc'),
  );

/*  
  $items['conjoc/verb_autocomplete_gasc_validate'] = array(
    'page callback' => 'ajax_conjoc_verb_autocomplete_validate',
    'file' => 'conjoc_lengadocian_webForm.inc',
    'type' => MENU_CALLBACK,
    'access arguments' => array('access conjoc'),
  );
*/  
  
  $items['lengadocian/verb_autocomplete_leng_submit'] = array(
    'page callback' => 'ajax_lengadocian_verb_autocomplete_submit',
    'file' => 'conjoc_lengadocian_webForm.inc',
    'type' => MENU_CALLBACK,
    'access arguments' => array('access conjoc'),
  );
  
  $items['lengadocian/verb_autocomplete_callback'] = array(
    'page callback' => 'ajax_lengadocian_verb_autocomplete_callback',
    'file' => 'conjoc_lengadocian_webForm.inc',
    'type' => MENU_CALLBACK,
    'access arguments' => array('access conjoc'),
  );

  $items['lengadocian/verb_autocomplete/usuals'] = array(
    'title' => t("Conjugador occitan"),
    'page callback' => '_lengadocian_menu_page',
    'access arguments' => array('access conjoc'),
    'file' => 'conjoc_lengadocian_webForm.inc',
    'type' => MENU_CALLBACK,
  );

  $items['lengadocian/verb_autocomplete/better_see'] = array(
    'title' => t("Conjugador occitan"),
    'page callback' => '_lengadocian_menu_page',
    'access arguments' => array('access conjoc'),
    'file' => 'conjoc_lengadocian_webForm.inc',
    'type' => MENU_CALLBACK,
  );

  $items['lengadocian/verb_autocomplete/singles'] = array(
    'title' => t("Conjugador occitan"),
    'page callback' => '_lengadocian_menu_page',
    'access arguments' => array('access conjoc'),
    'file' => 'conjoc_lengadocian_webForm.inc',
    'type' => MENU_CALLBACK,
  );

  $items['lengadocian/verb_autocomplete/top20'] = array(
    'title' => t("Conjugador occitan"),
    'page callback' => '_conjoc_menu_page',
    'access arguments' => array('access conjoc'),
    'file' => 'conjoc_lengadocian_webForm.inc',
    'type' => MENU_CALLBACK,
  );

  $items['lengadocian/TEI/exportLengadocian'] = array(
    'title' => t("Export TEI Lengadocian"),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('tei_export_lengadocian_all'),
    'access arguments' => array('admin conjoc'),
    'file' => 'conjoc_lengadocian_webForm.inc',
    'weight' => 10,
  );

  $items['lengadocian/Indexation/allLengadocian'] = array(
    'title' => t("Indexation Lengadocian"),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('indexation_lengadocian_all'),
    'access arguments' => array('admin conjoc'),
    'file' => 'conjoc_lengadocian_webForm.inc',
    'weight' => 10,
  );

  $items['lengadocian/Indexation/searchform'] = array(
    'title' => t("Indexation search form"),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('indexation_searchform'),
    'access arguments' => array('access conjoc'),
    'file' => 'conjoc_lengadocian_webForm.inc',
    'weight' => 10,
  );

  $items['conjoc/indexation_search/%/%'] = array(
    'title' => 'Indexation search',
    'page callback' => 'process_URL_arguments',
    'file' => 'conjoc_lengadocian_webForm.inc',
    'page arguments' => array(2,3),
    'access callback' => TRUE,
  );

  $items['conjoc/verb_autocomplete_indexation_callback'] = array(
    'page callback' => 'verb_autocomplete_indexation_callback',
    'file' => 'conjoc_lengadocian_webForm.inc',
    'type' => MENU_CALLBACK,
    'access arguments' => array('access conjoc'),
  );

  $items['conjoc/verb_autocomplete_indexation_submit'] = array(
    'page callback' => 'verb_autocomplete_indexation_submit',
    'file' => 'conjoc_lengadocian_webForm.inc',
    'type' => MENU_CALLBACK,
    'access arguments' => array('access conjoc'),
  );

  /*
    PROVENCAL
 

  $items['conjoc/provencal'] = array(
    'title' => t("Conjugador occitan dialecte provencal"),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ajax_provencal_verb_autocomplete'),
    'access arguments' => array('access conjoc'),
    'file' => 'conjoc_provencal_webForm.inc',
    'weight' => 10,
  );

  $items['conjoc/verb_autocomplete_prov_callback'] = array(
    'page callback' => 'ajax_provencal_verb_autocomplete_callback',
    'file' => 'conjoc_provencal_webForm.inc',
    'type' => MENU_CALLBACK,
    'access arguments' => array('access conjoc'),
  );
  */
  
  /*
    GASCON
  */

  $items['conjoc/gascon'] = array(
    'title' => t("Conjugador occitan dialecte gascon"),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ajax_gascon_verb_autocomplete'),
    'access arguments' => array('access conjoc'),
    'file' => 'conjoc_gascon_webForm.inc',
    'weight' => 10,
  );

  $items['conjoc/verb_autocomplete_gasc_callback'] = array(
    'page callback' => 'ajax_gascon_verb_autocomplete_callback',
    'file' => 'conjoc_gascon_webForm.inc',
    'type' => MENU_CALLBACK,
    'access arguments' => array('access conjoc'),
  );

/*  
  $items['conjoc/verb_autocomplete_gasc_validate'] = array(
    'page callback' => 'ajax_conjoc_verb_autocomplete_validate',
    'file' => 'conjoc_gascon_webForm.inc',
    'type' => MENU_CALLBACK,
    'access arguments' => array('access conjoc'),
  );
*/  

  
  $items['conjoc/verb_autocomplete_gasc_submit'] = array(
    'page callback' => 'ajax_conjoc_verb_autocomplete_submit',
    'file' => 'conjoc_gascon_webForm.inc',
    'type' => MENU_CALLBACK,
    'access arguments' => array('access conjoc'),
  );

  /*
    D E B U G
  */

  $items['conjoc/debug'] = array(
    'title' => t("Conjugador occitan dialecte debug"),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ajax_debug_verb_autocomplete'),
    'access arguments' => array('access conjoc'),
    'file' => 'conjoc_debug_webForm.inc',
    'weight' => 10,
  );

  $items['conjoc/verb_autocomplete_debug_callback'] = array(
    'page callback' => 'ajax_debug_verb_autocomplete_callback',
    'file' => 'conjoc_debug_webForm.inc',
    'type' => MENU_CALLBACK,
    'access arguments' => array('access conjoc'),
  );

  $items['conjoc/verb_autocomplete_debug_submit'] = array(
    'page callback' => 'ajax_debug_verb_autocomplete_submit',
    'file' => 'conjoc_debug_webForm.inc',
    'type' => MENU_CALLBACK,
    'access arguments' => array('access conjoc'),
  );

  $items['conjoc/debug_submit'] = array(
    'page callback' => 'ajax_debug_verb_autocomplete_submit',
    'file' => 'conjoc_debug_webForm.inc',
    'type' => MENU_CALLBACK,
    'access arguments' => array('access conjoc'),
  );

  $items['conjoc/debug_TEI_submit'] = array(
    'page callback' => 'ajax_debug_verb_autocomplete_submit',
    'file' => 'conjoc_debug_webForm.inc',
    'type' => MENU_CALLBACK,
    'access arguments' => array('access conjoc'),
  );

  return $items;
}



/**
 * Implements hook_permission().
 *
 * Provides a demonstration access string.
 */
function conjoc_permission() {
  return array(
    'access conjoc' => array(
      'title' => t('Access the protected conjoc menu'),
    ),
    'admin conjoc' => array(
      'title' => t('Administer conjoc content'),
    ),
  );

}

